version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./sites:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.docker
        volumes:
            - ./sites:/var/www
        links:
            - mysql
            - redis
    mysql:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=1234"
            - "MYSQL_DATABASE=docker_app"
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - mysql
        ports:
            - 8183:80
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: 1234
            PMA_ARBITRARY: 1
    redis:
        image: redis:alpine
        ports:
            - "63791:6379"
